url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: project_B
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Jonas Biehler
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #

- name: Kei MÃ¼ller
  pic: 2
  position: CEO
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #

- name: Peter
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #
      
- name: Lena Yoshihara
  pic: 4
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #
      
- name: Wolfgang Wall
  pic: 5
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #
      
- name: Karl Wichmann
  pic: 6
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: linkedin
    url: http://twitter.com/jekyllrb
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
